# Compilers
CC = mpiicc
LINK = $(CC)

# Common flags
# Debug mode
PEVSL_DEBUG = -DPEVSL_DEBUG
FLAGS = -DUNIX -O3 -g -Wall $(PEVSL_DEBUG) $(TIMING)

##OBJ_TIME = mactime.o
OBJ_TIME = timing.o 

# ar 
AR = ar rv
RANLIB = ranlib

#LIB0 = -lrt -lm #-lgfortran 
LIBLAPACK =  -lmkl_intel_lp64 -lmkl_sequential -lmkl_intel_thread -lmkl_core -lmkl_lapack95_lp64 -lmkl_blas95_lp64 -lpthread -lm

