all:
	( cd Chebiter   ; make )
	( cd Direct     ; make )
	( cd Matvec     ; make )
	( cd MUMPS      ; make )
	
clean:
	( cd Chebiter   ; make clean)
	( cd Direct     ; make clean)
	( cd Matvec     ; make clean)
	( cd MUMPS      ; make clean)
